### ISSUE TITLE
tool-pioasm (or similar) not published on the PlatformIO registry

### ISSUE THREAD

**Issue by josephduchesne** [earlephilhower/pico-quick-toolchain#34]
I'm able to work around it by adding the following to platformio.ini: 
```
platform_packages = 
    tool-pioasm-rp2040-earlephilhower @ https://github.com/earlephilhower/pico-quick-toolchain/releases/download/2.1.0-a/x86_64-linux-gnu.pioasm-6a7db34.230911.tar.gz
```

However that's not portable at all. I'm not sure why it disappeared when at least one other packages in this repo is still there.

**Comment by earlephilhower** [comment]
Sorry, but Platform.IO has chosen not to support the RP2040, and asked me to not publish packages.  So anything in the P.IO repos is pretty ancient.

See https://github.com/platformio/platform-raspberrypi/pull/36 for the discussion and https://github.com/earlephilhower/arduino-pico/blob/master/docs/platformio.rst for current docs.

**Comment by josephduchesne** [comment]
I was afraid of that. I've already ranted a bit (politely) in that discussion around a year ago. Hopefully they come to their senses one of these years.
