### ISSUE TITLE
Publish packets to PlatformIO registry

### ISSUE THREAD

**Issue by maxgerhardt** [earlephilhower/pico-quick-toolchain#5]
To make usage of these packages even easier in a platform, the packages should be published to the PlatformIO trusted registry, with [`pio package publish`](https://docs.platformio.org/en/latest/core/userguide/package/cmd_publish.html) (and a PlatformIO account of course / previous `pio account login`)

The `package.json` in the generated releases is already correct, however one nitpick I'd have is to use more 'traditional' naming. E.g., the OpenOCD `package.json` has as `name` field `openocd` -- (Helper)Tools in PlatformIO have a `tool-` prefix (toolchains have `toolchain-` prefix). PlatformIO already has `tool-openocd`, but more importantly `tool-openocd-raspberrypi` which is currently used in https://github.com/platformio/platform-raspberrypi. You can choose a unique name here (e.g. `tool-openocd-pico` or `tool-openocd-raspberrypi-earlephilhower`), but or also `tool-openocd-rasberrypi` (PlatformIO can distinguish by `owner` name, but you will get a warning for the name already being taken at upload).

`toolchain-pico` for the compiler is fine. 

`pioasm` should be renamed to `tool-pioasm` though.

`tool-mklittlefs` doesn't need to uploaded because PlatformIO [already has it](https://api.registry.platformio.org/v3/packages/platformio/tool/tool-mklittlefs), same for `elf2uf2` (in `tool-rp2040tools`). 

Note that before publishing, issue #4 should be investigated.

**Comment by earlephilhower** [comment]
@maxgerhardt let me know if I did the `pio package publish` properly.  I published all the files I upload to the release, and it's now a `make` target so will be automated on future revs.
