### ISSUE TITLE
picod-debug.cfg references nonexisting rp2040-core0.cfg

### ISSUE THREAD

**Issue by maxgerhardt** [earlephilhower/pico-quick-toolchain#61]
Not sure if relevant or not since https://github.com/majbthrd/pico-debug has even been archived as of now.

With https://github.com/earlephilhower/pico-quick-toolchain/releases/download/2.2.0/x86_64-w64-mingw32.openocd-ebec9504d.240827.zip

The `board/pico-debug.cfg` says
```
# SPDX-License-Identifier: GPL-2.0-or-later
# pico-debug is a virtual CMSIS-DAP debug adapter
# it runs on the very same RP2040 target being debugged without additional hardware
# https://github.com/majbthrd/pico-debug

source [find interface/cmsis-dap.cfg]
adapter speed 4000

set CHIPNAME rp2040
source [find target/rp2040-core0.cfg]
```
but there is no such file.

![grafik](https://github.com/user-attachments/assets/cd38b334-25bb-440c-b0f6-02ad2f937768)

**Comment by earlephilhower** [comment]
Yeah, looks like it's abandoned.  Will just from the Arduino Core menus and P.IO JSONs.
