### ISSUE TITLE
GCC 14.02 for arm compiling aduino-pico package fails using /tools/libpico/make-libpico.sh

### ISSUE THREAD

**Issue by morio** [earlephilhower/pico-quick-toolchain#65]
I have to spin a custom version of the arduino-pico, which means I have to rebuild the static libraries.
I decided to use the https://github.com/earlephilhower/pico-quick-toolchain/releases/tag/4.0.1 arm and riscv gcc tools to do the rebuild, because it is the same toolchain that will build our firmware, but I run into this error
```
+ arm-none-eabi-gcc -march=armv6-m -mcpu=cortex-m0plus -mthumb -O3 -DNDEBUG -DPICO_FLASH_SPI_CLKDIV=2 -c /home/rabbit/vanilla/arduino-pico/pico-sdk/src/rp2040/boot_stage2/boot2_w25x10cl.S -I /home/rabbit/vanilla/arduino-pico/pico-sdk/src/boards/include/boards/ -I /home/rabbit/vanilla/arduino-pico/pico-sdk/src/rp2040/hardware_regs/include/ -I /home/rabbit/vanilla/arduino-pico/pico-sdk/src/rp2_common/pico_platform/include/ -I /home/rabbit/vanilla/arduino-pico/pico-sdk/src/rp2_common/boot_stage2/asminclude/ -I /home/rabbit/vanilla/arduino-pico/pico-sdk/src/rp2040/pico_platform/include/ -I /home/rabbit/vanilla/arduino-pico/pico-sdk/src/rp2040/boot_stage2/asminclude/ -I .
/home/rabbit/vanilla/arduino-pico/pico-sdk/src/rp2040/boot_stage2/boot2_w25x10cl.S: Assembler messages:
/home/rabbit/vanilla/arduino-pico/pico-sdk/src/rp2040/boot_stage2/boot2_w25x10cl.S:147: Error: junk at end of line, first unrecognized character is `0'
/home/rabbit/vanilla/arduino-pico/pico-sdk/src/rp2040/boot_stage2/boot2_w25x10cl.S:150: Error: garbage following instruction -- `beq 00b'
```
This is a build from adruino-pico with no modifications from https://github.com/earlephilhower/arduino-pico
gcc 12.4 from release 2.3.0 compiles without errors and the riscv gcc 14.02 seem to compile the similar file `https://github.com/raspberrypi/pico-sdk/blob/master/src/rp2350/boot_stage2/boot2_w25x10cl.S`

I know the file lives with the pico-sdk and changing lines
https://github.com/raspberrypi/pico-sdk/blob/efe2103f9b28458a1615ff096054479743ade236/src/rp2040/boot_stage2/boot2_w25x10cl.S#L147-L150
to 

```
0:
    ldr r0, [r3, #SSI_SR_OFFSET]    // Read status register
    tst r0, r1                      // RFNE status flag set?
    beq 0b                         // If not then wait
```

from

```
00:
    ldr r0, [r3, #SSI_SR_OFFSET]    // Read status register
    tst r0, r1                      // RFNE status flag set?
    beq 00b                         // If not then wait
 ```
 
 lets the arm gcc 14.02 compile without errors. But I'm wondering if there is a bug in the arm gcc 14.02 causing the error rather than Raspberry Pi's pico-sdk need to change their label in the assembly state 2 bootloader.
 
 Cheers,
 - Morio

**Comment by earlephilhower** [comment]
Interesting find!  I suggest you open something up on the pico-sdk repo so this gets cleaned up in the next release.  There's nothing here to be done, really, as we use gcc14.1 with no patches at all.
